###consul服务端口号
server:
  port: 80

spring:
  application:
    name: consul-consumer-order
  ####consul注册中心地址
  cloud:
    consul:
      host: 192.168.216.132
      port: 8500
      discovery:
        hostname: 192.168.216.6 #提供服务地址
        service-name: ${spring.application.name}
        health-check-path: /actuator/health

